#define au auto
#define br break
#define ch char
#define cn continue
#define cs case
#define ct const
#define db double
#define de default
#define el else
#define en enum
#define ex extern
#define fl float
#define go goto
#define in int
#define il inline
#define lo long
#define rg register
#define rs restrict
#define rt return
#define sc static
#define sd signed
#define sh short
#define st struct
#define sw switch
#define sz sizeof
#define ty typedef
#define un union
#define us unsigned
#define vo void
#define vl 